name: CI

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

  - name: Train model (auto-detect version)
    run: |
      echo "🔹 GitHub ref name: ${{ github.ref_name }}"
      if [[ "${{ github.ref_name }}" == "v0.1"* ]]; then
        echo "➡️ Training LinearRegression (v0.1)"
        python train.py
      elif [[ "${{ github.ref_name }}" == "v0.2"* ]]; then
        echo "➡️ Training Ridge model (v0.2)"
        python train_v2.py
      else
        echo "⚠️ Defaulting to train.py (no version detected)"
        python train.py
      fi
```
