name: Release Model Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show GitHub tag
        run: echo "GitHub tag: ${{ github.ref_name }}"

      - name: Train model based on tag
        run: |
          TAG="${{ github.ref_name }}"
          echo "Training for tag $TAG"
          if [[ "$TAG" == v0.1* ]]; then
            python train.py
          elif [[ "$TAG" == v0.2* ]]; then
            python train_v2.py
          else
            echo "No matching train script"
            exit 1
          fi

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model/

      - name: Attach model files to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            model/model.joblib
            model/metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
