name: Release Model Docker Image

on:
  release:
    types: [published]   # Triggered when you create a GitHub release

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Determine version from tag
      - name: Show GitHub tag
        run: echo "GitHub tag: ${GITHUB_REF_NAME}"

      # Build Docker image with correct MODEL_VERSION
      - name: Build Docker image
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          echo "Building Docker image for $TAG_NAME"
          if [[ "$TAG_NAME" == v0.1* ]]; then
            docker build --build-arg MODEL_VERSION=v0.1 -t virtual-diabetes:v0.1 .
          elif [[ "$TAG_NAME" == v0.2-rf* ]]; then
            docker build --build-arg MODEL_VERSION=v0.2-rf -t virtual-diabetes:v0.2-rf .
          elif [[ "$TAG_NAME" == v0.2* ]]; then
            docker build --build-arg MODEL_VERSION=v0.2 -t virtual-diabetes:v0.2 .
          else
            echo "No matching model version for tag $TAG_NAME"
            exit 1
          fi

      # Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push Docker image to GHCR
      - name: Push Docker image
        run: |
          if [[ "$TAG_NAME" == v0.1* ]]; then
            docker tag virtual-diabetes:v0.1 ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.1
            docker push ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.1
          elif [[ "$TAG_NAME" == v0.2-rf* ]]; then
            docker tag virtual-diabetes:v0.2-rf ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.2-rf
            docker push ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.2-rf
          elif [[ "$TAG_NAME" == v0.2* ]]; then
            docker tag virtual-diabetes:v0.2 ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.2
            docker push ghcr.io/${{ github.repository_owner }}/virtual-diabetes:v0.2
          fi

      # Upload model artifacts (joblib + metrics.json)
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model/

      # Attach model files to GitHub release
      - name: Attach model files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            model/model.joblib
            model/metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
