name: Train and Release Model

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          echo "GitHub tag: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == v0.1* ]]; then
            python train.py
          elif [[ "${{ github.ref_name }}" == v0.2* ]]; then
            python train_v2.py
          else
            echo "No matching train script for tag ${{ github.ref_name }}"
            exit 1
          fi

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model/

      - name: Build and push Docker image to GHCR
        run: |
          # The repository name (e.g., alyssafubuki-collab/MAIO-assignment-3-group-BB)
          REPO_WITH_CASE="${{ github.repository }}"
          # Convert to lowercase (e.g., alyssafubuki-collab/maio-assignment-3-group-bb)
          LOWER_REPO=$(echo "$REPO_WITH_CASE" | tr '[:upper:]' '[:lower:]')
          
          # The final, correct image tag
          IMAGE_NAME="ghcr.io/$LOWER_REPO:${{ github.ref_name }}"
          
          echo "🔧 Building Docker image: $IMAGE_NAME"
          docker build -t "$IMAGE_NAME" .
          echo "Logging into GitHub Container Registry"
          # Use GITHUB_TOKEN for authentication
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          echo "Pushing Docker image..."
          docker push "$IMAGE_NAME"

      - name: Attach model files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            model/model.joblib
            model/metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
