name: Train and Release Model

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          echo "GitHub tag: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == v0.1* ]]; then
            python train.py
          elif [[ "${{ github.ref_name }}" == v0.2* ]]; then
            python train_v2.py
          else
            echo "No matching train script for tag ${{ github.ref_name }}"
            exit 1
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          echo "Built image: $IMAGE_NAME"

      - name: Smoke test container
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker run --rm $IMAGE_NAME python -c "print('Container test passed')"

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push $IMAGE_NAME
          echo " Pushed image: $IMAGE_NAME"

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model/

      - name: Attach model files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            model/model.joblib
            model/metrics.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
