name: Release

on:
  push:
    tags:
      - 'v*'  # déclenche le workflow sur push de tag v0.1, v0.2, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: python train.py

    - name: Check model files
      run: ls -l model/  # vérifie que model.joblib et metrics.json sont créés

    - name: Upload model artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: model/   # on upload tout le dossier "model"

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
       tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: "Automated release of virtual-diabetes"
        files: |
          model/model.joblib
          model/metrics.json
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: "Automated release of virtual-diabetes"
